<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelAccountNumber</name>
   <tag></tag>
   <elementGuidId>b1a1d836-6dba-4478-a1df-906d0f56e4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='receipt__info'][2]/preceding-sibling::div[@class='receipt__info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='receipt__info'][2]/preceding-sibling::div[@class='receipt__info']</value>
   </webElementProperties>
</WebElementEntity>
