<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonCreateRefund</name>
   <tag></tag>
   <elementGuidId>5b86d414-7aad-415a-b61f-e63f4a232433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='button-send__refund']//a[@class='button-send__link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='button-send__refund']//a[@class='button-send__link']</value>
   </webElementProperties>
</WebElementEntity>
